### ISSUE TITLE
Can not open any archived page

### ISSUE THREAD

**Issue by RuralHunter** [GChristensen/scrapyard#88]
All the archived page show this same error:
```
Traceback (most recent call last): 
File "/home/rhunter/.local/lib/python3.9/site-packages/flask/app.py", line 1516, in full_dispatch_request rv = self.dispatch_request() 
File "/home/rhunter/.local/lib/python3.9/site-packages/flask/app.py", line 1492, in dispatch_request self.raise_routing_exception(req) 
File "/home/rhunter/.local/lib/python3.9/site-packages/flask/app.py", line 1474, in raise_routing_exception raise request.routing_exception # type: ignore 
File "/home/rhunter/.local/lib/python3.9/site-packages/flask/ctx.py", line 367, in match_request result = self.url_adapter.match(return_rule=True) # type: ignore 
File "/home/rhunter/.local/lib/python3.9/site-packages/werkzeug/routing.py", line 2041, in match raise NotFound() werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again. 
```
What can I do?

**Comment by GChristensen** [comment]
Hi,

It is impossible to determine the reason from the stack trace. I'd check if the folder with the archived content exists, has the correct permissions, and restart the machine.

**Comment by RuralHunter** [comment]
I checked the storage folder and content and they are no problem. I can still archive new page and I can see the content generated in the storage folder but just can not view it in scrapyard. I haven't used scrapyard for a while and got this problem when I  used it recently. Is there anything I need to upgrade but I missed?

**Comment by GChristensen** [comment]
The next thing to check if the path of the archived content folder in the settings is correct and the same. The stack trace hints that the app works, but can't find the content. If the path is the same, it is worth to reinstall the background python app.

**Comment by RuralHunter** [comment]
Thanks, I upgraded the backend app and re-imported the rdf.
